apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail-rs-spring
  labels:
    name: trail1-spring
spec:
  minReadySeconds: 10
  replicas: 3
  selector: 
    matchLabels:
      app: petc
  template:
    metadata:
      labels:
        app: petc
        env: dev
        version: "1.0"
    spec:
      containers: 
        - name: springpetclinic
          image: dockerbhadhragiri/petc:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: svc-spring
spec:
  type: NodePort
  selector:
    app: petc
  ports:
    - name: portpetc
      targetPort: 8080
      port: 8080
      nodePort: 30001
