apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-alpine
  labels: 
    name: activity
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: web
        version: "1.0"
    spec:
      containers: 
        - name: web
          image: alpine
          ports:
            - containerPort: 80
          args:
            - sleep
            - 1d
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80