apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-yml
spec:
  schedule: "0 1 * * 1-5"
  jobTemplate:
    metadata:
      name: dummy-job
    spec: 
      template:
        metadata:
          name: dummy-pod
          labels: 
            app: job
        spec:
          restartPolicy: Never
          containers: 
            - name: dummy-ctr
              image: alpine
              args:
                - sleep
                - 30s
          