---
apiVersion: v1
kind: Pod
metadata:
  name: podd
spec:
  containers:
    - name: httpdpod
      image: httpd:2.4
      ports:
        - containerPort: 80
    - name: jenkinspod
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
    
      