apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail-rs
  labels:
    name: trail-http-label
spec:
  minReadySeconds: 10
  replicas: 3
  selector: 
    matchLabels:
      app: httpdlabel
  template:
    metadata:
      labels:
        app: httpdlabel
        env: dev
        version: "1.0"
    spec:
      containers: 
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80