---
apiVersion: v1
kind: Pod
metadata: 
  name: trail-pod
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: trail-c
      image: alpine
      args:
        - sleep
        - 30s
  containers:
    - name: sidecar
      image: nginx
      resources:
        limits:
          cpu: 1000m
          memory: 0.5Gi
