apiVersion: v1
kind: ReplicationController
metadata:
  name: RC1
  labels: 
    name: RC123
spec:
  minReadySeconds: 10
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: "1.0"
    spec:
      containers: 
        - name: nginx
          image: nginx