---
apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
    - name: limits-container
      image: jenkins/jenkins
      resources:
        requests:
          cpu: 800m
          memory: 700Mi
        limits:
          cpu: 1000m
          memory: 0.8Gi
